import sqlite3


def fillDatabase():
    con = sqlite3.connect("trainstationDB.db")
    cursor = con.cursor()

    cursor.execute('INSERT INTO Trainstation VALUES (0,"Bodø",4.1)')
    cursor.execute('INSERT INTO Trainstation VALUES (1,"Fauska",34.0)')
    cursor.execute('INSERT INTO Trainstation VALUES (2,"Mo i Rana",3.5)')
    cursor.execute('INSERT INTO Trainstation VALUES (3,"Mosjøen",6.8)')
    cursor.execute('INSERT INTO Trainstation VALUES (4,"Steinkjer",3.6)')
    cursor.execute('INSERT INTO Trainstation VALUES (5,"Trondheim",5.1)')

    cursor.execute('INSERT INTO TrackStretch VALUES (0,"Nordlandsbanen","El",0,5)')

    cursor.execute("INSERT INTO PartialTrackStretch VALUES (0,0,60,1,0,1)")
    cursor.execute("INSERT INTO PartialTrackStretch VALUES (1,0,170,1,1,2)")
    cursor.execute("INSERT INTO PartialTrackStretch VALUES (2,0,90,1,2,3)")
    cursor.execute("INSERT INTO PartialTrackStretch VALUES (3,0,280,1,3,4)")
    cursor.execute("INSERT INTO PartialTrackStretch VALUES (4,0,120,2,4,5)")

    cursor.execute("INSERT INTO IntermediateStationOnTrackStretch VALUES (0,0)")
    cursor.execute("INSERT INTO IntermediateStationOnTrackStretch VALUES (0,1)")
    cursor.execute("INSERT INTO IntermediateStationOnTrackStretch VALUES (0,2)")
    cursor.execute("INSERT INTO IntermediateStationOnTrackStretch VALUES (0,3)")
    cursor.execute("INSERT INTO IntermediateStationOnTrackStretch VALUES (0,4)")
    cursor.execute("INSERT INTO IntermediateStationOnTrackStretch VALUES (0,5)")

    cursor.execute('INSERT INTO Wagon VALUES (0,"Wagon_1")')
    cursor.execute('INSERT INTO Wagon VALUES (1,"Wagon_2")')
    cursor.execute('INSERT INTO Wagon VALUES (2,"Wagon_1")')
    cursor.execute('INSERT INTO Wagon VALUES (3,"Wagon_2")')
    cursor.execute('INSERT INTO Wagon VALUES (4,"Wagon_2")')
    cursor.execute("INSERT INTO SittingWagon VALUES (0,3,4)")
    cursor.execute("INSERT INTO SittingWagon VALUES (1,3,4)")
    cursor.execute("INSERT INTO SleepingWagon VALUES (2,4)")
    cursor.execute("INSERT INTO SittingWagon VALUES (3,3,4)")
    cursor.execute("INSERT INTO SittingWagon VALUES (4,3,4)")

    cursor.execute('INSERT INTO Operator VALUES (0,"SJ")')
    cursor.execute('INSERT INTO Operator VALUES (1,"SJ")')
    cursor.execute('INSERT INTO Operator VALUES (2,"SJ")')

    cursor.execute("INSERT INTO OperatorOwnsVagon VALUES (0,0)")
    cursor.execute("INSERT INTO OperatorOwnsVagon VALUES (0,1)")
    cursor.execute("INSERT INTO OperatorOwnsVagon VALUES (1,2)")
    cursor.execute("INSERT INTO OperatorOwnsVagon VALUES (1,3)")
    cursor.execute("INSERT INTO OperatorOwnsVagon VALUES (2,4)")

    cursor.execute('INSERT INTO WeekDay VALUES (0,"Monday")')
    cursor.execute('INSERT INTO WeekDay VALUES (1,"Thirday")')
    cursor.execute('INSERT INTO WeekDay VALUES (2,"Wednesday")')
    cursor.execute('INSERT INTO WeekDay VALUES (3,"Tuesday")')
    cursor.execute('INSERT INTO WeekDay VALUES (4,"Friday")')
    cursor.execute('INSERT INTO WeekDay VALUES (5,"Saturday")')
    cursor.execute('INSERT INTO WeekDay VALUES (6,"Sunday")')

    cursor.execute("INSERT INTO TrainRoute VALUES (0,5,0,7.49,17.34,0,0)")
    cursor.execute("INSERT INTO TrainRoute VALUES (1,5,0,23.05,09.05,0,1)")
    cursor.execute("INSERT INTO TrainRoute VALUES (2,2,5,8.11,14.13,0,2)")

    cursor.execute("INSERT INTO IntermediateStationOnTrainRoute VALUES (0,1,0,0)")
    cursor.execute("INSERT INTO IntermediateStationOnTrainRoute VALUES (0,2,0,0)")
    cursor.execute("INSERT INTO IntermediateStationOnTrainRoute VALUES (0,3,0,0)")
    cursor.execute("INSERT INTO IntermediateStationOnTrainRoute VALUES (0,4,0,0)")
    cursor.execute("INSERT INTO IntermediateStationOnTrainRoute VALUES (1,1,0,0)")
    cursor.execute("INSERT INTO IntermediateStationOnTrainRoute VALUES (1,2,0,0)")
    cursor.execute("INSERT INTO IntermediateStationOnTrainRoute VALUES (1,3,0,0)")
    cursor.execute("INSERT INTO IntermediateStationOnTrainRoute VALUES (1,4,0,0)")
    cursor.execute("INSERT INTO IntermediateStationOnTrainRoute VALUES (2,3,0,0)")
    cursor.execute("INSERT INTO IntermediateStationOnTrainRoute VALUES (2,4,0,0)")

    cursor.execute("INSERT INTO WagonLayout VALUES (0,0,1)")
    cursor.execute("INSERT INTO WagonLayout VALUES (0,1,2)")
    cursor.execute("INSERT INTO WagonLayout VALUES (1,2,2)")
    cursor.execute("INSERT INTO WagonLayout VALUES (1,3,1)")
    cursor.execute("INSERT INTO WagonLayout VALUES (2,4,1)")

    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (0,0)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (0,1)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (0,2)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (0,3)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (0,4)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (0,5)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (0,6)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (1,0)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (1,1)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (1,2)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (1,3)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (1,4)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (1,5)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (1,6)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (2,0)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (2,1)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (2,2)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (2,3)")
    cursor.execute("INSERT INTO TrainRouteRunsWeekdays VALUES (2,4)")

    con.commit()
    con.close()
